# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 581, 161))
        self.groupBox.setObjectName("groupBox")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonConnect.setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 30, 165, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelHost = QtWidgets.QLabel(self.widget)
        self.labelHost.setObjectName("labelHost")
        self.horizontalLayout.addWidget(self.labelHost)
        self.lineEditHost = QtWidgets.QLineEdit(self.widget)
        self.lineEditHost.setObjectName("lineEditHost")
        self.horizontalLayout.addWidget(self.lineEditHost)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 60, 165, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPort = QtWidgets.QLabel(self.widget1)
        self.labelPort.setObjectName("labelPort")
        self.horizontalLayout_2.addWidget(self.labelPort)
        self.lineEditPort = QtWidgets.QLineEdit(self.widget1)
        self.lineEditPort.setObjectName("lineEditPort")
        self.horizontalLayout_2.addWidget(self.lineEditPort)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 250, 571, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 80, 252, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelTopicPub = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelTopicPub.setObjectName("labelTopicPub")
        self.horizontalLayout_5.addWidget(self.labelTopicPub)
        self.lineEditTopicPub = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditTopicPub.setObjectName("lineEditTopicPub")
        self.horizontalLayout_5.addWidget(self.lineEditTopicPub)
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(40, 30, 252, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelTopicSub = QtWidgets.QLabel(self.widget2)
        self.labelTopicSub.setObjectName("labelTopicSub")
        self.horizontalLayout_3.addWidget(self.labelTopicSub)
        self.lineEditTopicSub = QtWidgets.QLineEdit(self.widget2)
        self.lineEditTopicSub.setObjectName("lineEditTopicSub")
        self.horizontalLayout_3.addWidget(self.lineEditTopicSub)
        self.pushButtonSub = QtWidgets.QPushButton(self.widget2)
        self.pushButtonSub.setObjectName("pushButtonSub")
        self.horizontalLayout_3.addWidget(self.pushButtonSub)
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(40, 110, 240, 25))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMsgPub = QtWidgets.QLabel(self.widget3)
        self.labelMsgPub.setObjectName("labelMsgPub")
        self.horizontalLayout_6.addWidget(self.labelMsgPub)
        self.lineEditMsgPub = QtWidgets.QLineEdit(self.widget3)
        self.lineEditMsgPub.setObjectName("lineEditMsgPub")
        self.horizontalLayout_6.addWidget(self.lineEditMsgPub)
        self.pushButtonPub = QtWidgets.QPushButton(self.widget3)
        self.pushButtonPub.setObjectName("pushButtonPub")
        self.horizontalLayout_6.addWidget(self.pushButtonPub)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButtonConnect.setText(_translate("MainWindow", "connect"))
        self.labelHost.setText(_translate("MainWindow", "host"))
        self.lineEditHost.setText(_translate("MainWindow", "iot.eclipse.org"))
        self.labelPort.setText(_translate("MainWindow", "port"))
        self.lineEditPort.setText(_translate("MainWindow", "1883"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.labelTopicPub.setText(_translate("MainWindow", "topic"))
        self.lineEditTopicPub.setText(_translate("MainWindow", "pyqttopic/light"))
        self.labelTopicSub.setText(_translate("MainWindow", "topic"))
        self.lineEditTopicSub.setText(_translate("MainWindow", "pyqttopic/#"))
        self.pushButtonSub.setText(_translate("MainWindow", "subscribe"))
        self.labelMsgPub.setText(_translate("MainWindow", "msg"))
        self.lineEditMsgPub.setText(_translate("MainWindow", "on"))
        self.pushButtonPub.setText(_translate("MainWindow", "publish"))

