# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 641, 241))
        self.groupBox.setObjectName("groupBox")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonConnect.setGeometry(QtCore.QRect(480, 200, 75, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 458, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelHost = QtWidgets.QLabel(self.layoutWidget)
        self.labelHost.setMinimumSize(QtCore.QSize(50, 0))
        self.labelHost.setObjectName("labelHost")
        self.horizontalLayout.addWidget(self.labelHost)
        self.lineEditHost = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditHost.sizePolicy().hasHeightForWidth())
        self.lineEditHost.setSizePolicy(sizePolicy)
        self.lineEditHost.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditHost.setObjectName("lineEditHost")
        self.horizontalLayout.addWidget(self.lineEditHost)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 60, 458, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPort = QtWidgets.QLabel(self.layoutWidget1)
        self.labelPort.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPort.setObjectName("labelPort")
        self.horizontalLayout_2.addWidget(self.labelPort)
        self.lineEditPort = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPort.setObjectName("lineEditPort")
        self.horizontalLayout_2.addWidget(self.lineEditPort)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 90, 458, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPortClientId = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelPortClientId.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortClientId.setObjectName("labelPortClientId")
        self.horizontalLayout_4.addWidget(self.labelPortClientId)
        self.lineEditPortClientId = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortClientId.sizePolicy().hasHeightForWidth())
        self.lineEditPortClientId.setSizePolicy(sizePolicy)
        self.lineEditPortClientId.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortClientId.setObjectName("lineEditPortClientId")
        self.horizontalLayout_4.addWidget(self.lineEditPortClientId)
        self.pushButtonClientIdGenerate = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonClientIdGenerate.setGeometry(QtCore.QRect(480, 90, 75, 23))
        self.pushButtonClientIdGenerate.setObjectName("pushButtonClientIdGenerate")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 170, 458, 22))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelPortUserName = QtWidgets.QLabel(self.layoutWidget_8)
        self.labelPortUserName.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortUserName.setObjectName("labelPortUserName")
        self.horizontalLayout_14.addWidget(self.labelPortUserName)
        self.lineEditPortUserName = QtWidgets.QLineEdit(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortUserName.sizePolicy().hasHeightForWidth())
        self.lineEditPortUserName.setSizePolicy(sizePolicy)
        self.lineEditPortUserName.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortUserName.setText("")
        self.lineEditPortUserName.setObjectName("lineEditPortUserName")
        self.horizontalLayout_14.addWidget(self.lineEditPortUserName)
        self.layoutWidget_14 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_14.setGeometry(QtCore.QRect(20, 200, 458, 22))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.labelPort_12 = QtWidgets.QLabel(self.layoutWidget_14)
        self.labelPort_12.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPort_12.setObjectName("labelPort_12")
        self.horizontalLayout_21.addWidget(self.labelPort_12)
        self.lineEditPortPassword = QtWidgets.QLineEdit(self.layoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPortPassword.setSizePolicy(sizePolicy)
        self.lineEditPortPassword.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortPassword.setText("")
        self.lineEditPortPassword.setObjectName("lineEditPortPassword")
        self.horizontalLayout_21.addWidget(self.lineEditPortPassword)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 120, 330, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxCleanSession = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBoxCleanSession.setObjectName("checkBoxCleanSession")
        self.horizontalLayout_8.addWidget(self.checkBoxCleanSession)
        self.checkBoxAutoConnect = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBoxAutoConnect.setObjectName("checkBoxAutoConnect")
        self.horizontalLayout_8.addWidget(self.checkBoxAutoConnect)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelPortKeepAlive = QtWidgets.QLabel(self.layoutWidget2)
        self.labelPortKeepAlive.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortKeepAlive.setObjectName("labelPortKeepAlive")
        self.horizontalLayout_7.addWidget(self.labelPortKeepAlive)
        self.spinBoxKeepAlive = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBoxKeepAlive.setObjectName("spinBoxKeepAlive")
        self.horizontalLayout_7.addWidget(self.spinBoxKeepAlive)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 300, 651, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 180, 458, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelTopicPub = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelTopicPub.setMinimumSize(QtCore.QSize(50, 0))
        self.labelTopicPub.setObjectName("labelTopicPub")
        self.horizontalLayout_5.addWidget(self.labelTopicPub)
        self.lineEditTopicPub = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTopicPub.sizePolicy().hasHeightForWidth())
        self.lineEditTopicPub.setSizePolicy(sizePolicy)
        self.lineEditTopicPub.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditTopicPub.setObjectName("lineEditTopicPub")
        self.horizontalLayout_5.addWidget(self.lineEditTopicPub)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 539, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelTopicSub = QtWidgets.QLabel(self.layoutWidget3)
        self.labelTopicSub.setMinimumSize(QtCore.QSize(50, 0))
        self.labelTopicSub.setObjectName("labelTopicSub")
        self.horizontalLayout_3.addWidget(self.labelTopicSub)
        self.lineEditTopicSub = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTopicSub.sizePolicy().hasHeightForWidth())
        self.lineEditTopicSub.setSizePolicy(sizePolicy)
        self.lineEditTopicSub.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditTopicSub.setObjectName("lineEditTopicSub")
        self.horizontalLayout_3.addWidget(self.lineEditTopicSub)
        self.pushButtonSub = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButtonSub.setObjectName("pushButtonSub")
        self.horizontalLayout_3.addWidget(self.pushButtonSub)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 210, 539, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMsgPub = QtWidgets.QLabel(self.layoutWidget4)
        self.labelMsgPub.setMinimumSize(QtCore.QSize(50, 0))
        self.labelMsgPub.setObjectName("labelMsgPub")
        self.horizontalLayout_6.addWidget(self.labelMsgPub)
        self.lineEditMsgPub = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMsgPub.sizePolicy().hasHeightForWidth())
        self.lineEditMsgPub.setSizePolicy(sizePolicy)
        self.lineEditMsgPub.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditMsgPub.setObjectName("lineEditMsgPub")
        self.horizontalLayout_6.addWidget(self.lineEditMsgPub)
        self.pushButtonPub = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButtonPub.setObjectName("pushButtonPub")
        self.horizontalLayout_6.addWidget(self.pushButtonPub)
        self.textBrowserReceived = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowserReceived.setGeometry(QtCore.QRect(20, 60, 531, 101))
        self.textBrowserReceived.setObjectName("textBrowserReceived")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButtonConnect.setText(_translate("MainWindow", "connect"))
        self.labelHost.setText(_translate("MainWindow", "host"))
        self.lineEditHost.setText(_translate("MainWindow", "iot.eclipse.org"))
        self.labelPort.setText(_translate("MainWindow", "port"))
        self.lineEditPort.setText(_translate("MainWindow", "1883"))
        self.labelPortClientId.setText(_translate("MainWindow", "clientId"))
        self.lineEditPortClientId.setText(_translate("MainWindow", "pyqtclient_xxxxxxx"))
        self.pushButtonClientIdGenerate.setText(_translate("MainWindow", "generate"))
        self.labelPortUserName.setText(_translate("MainWindow", "username"))
        self.labelPort_12.setText(_translate("MainWindow", "password"))
        self.checkBoxCleanSession.setText(_translate("MainWindow", "CleanSession"))
        self.checkBoxAutoConnect.setText(_translate("MainWindow", "auto connect"))
        self.labelPortKeepAlive.setText(_translate("MainWindow", "keep alive(S)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.labelTopicPub.setText(_translate("MainWindow", "topic"))
        self.lineEditTopicPub.setText(_translate("MainWindow", "pyqttopic/light"))
        self.labelTopicSub.setText(_translate("MainWindow", "topic"))
        self.lineEditTopicSub.setText(_translate("MainWindow", "pyqttopic/#"))
        self.pushButtonSub.setText(_translate("MainWindow", "subscribe"))
        self.labelMsgPub.setText(_translate("MainWindow", "msg"))
        self.lineEditMsgPub.setText(_translate("MainWindow", "on"))
        self.pushButtonPub.setText(_translate("MainWindow", "publish"))

